# nixpacks.toml

[phases.setup]
# Для образов на базе Debian, aptPkgs является самым прямым способом установки системных бинарных файлов.
# FFmpeg является стандартным пакетом в репозиториях по умолчанию.
aptPkgs = ["ffmpeg"]
